//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:2.0.50727.3615
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GK2010.Web.Admin.ProductSpecial {
    
    
    public partial class Manage {
        		protected global::System.Web.UI.WebControls.Panel PanelSearch;
		protected global::System.Web.UI.WebControls.TextBox txtKey;
		protected global::System.Web.UI.WebControls.Button btnSearch;
		protected global::System.Web.UI.WebControls.GridView grid;
		protected global::Wuqi.Webdiyer.AspNetPager AspNetPager1;
		protected global::System.Web.UI.WebControls.Button btnDelete;
		protected global::System.Web.UI.WebControls.Button btnAdd;

    }
}
